export const apis = {
  allProducts: "/product_details",
  productDetails: "/",
  blogs: "/blog/blog_list",
  blogDetails: "/blog/",
  accountDetails: "/account_details",
  coupon: "/coupon_page",
  address: "/address_change",
  orders: "/orders",
  cashback: "/cashback",
  wishlist: "/wishlist",
  login: "/login",
  signup: "/signup_comp",
  address_change: "/address_change",
  homebanner: "/home/banner",
  topseller: "/topseller",
  instaPosts: "/insta_posts",
  deals: "/deals",
  blogCategory: "/list",
  productbanner: "/product/banner",
  cart: "/cart",
  header: "/header",
  testimonial: "/testimonial",
  tooltest: "/tooltest",
  toolpage: "/toolpage"
};
